name: CI
on:
  # Triggers the workflow on pull request against main
  pull_request:
    branches: [master, main]
  # Triggers the workflow on push to main
  push:
    branches: [master, main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install modules
        run: yarn

      - name: Run tests
        run: yarn test --runInBand
        env:
          MNEMONIC: ${{ secrets.MNEMONIC }}
          NETWORK: alfajores
